import Head from "next/head";
import { ConnectWalletButton } from "../components/molecules/connectWalletButton";
import Logo from "../components/atoms/logo/logo";

import style from "./index.module.css";
import { Input } from "../components/atoms/input";
import { InputVariant } from "../components/atoms/input/input";
import { useKeyPress } from "../hooks/useKeyPress";
import { useState } from "react";
import classNames from "classnames";
import { ResultItem } from "../components/atoms/resultItem";

export default function Home() {
  const [value, setValue] = useState("");
  const [resultContent, setResultContent] = useState({
    isShow: false,
    text: "",
  });

  const handleInput = () => {
    const isShow = !!value;
    setResultContent({
      text: value,
      isShow: isShow,
    });
  };

  useKeyPress("Enter", handleInput);

  return (
    <>
      <Head>
        <title>Mina Names</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classNames(style.wrapper, "container")}>
        <div className={style.header}>
          <Logo />
          <ConnectWalletButton />
        </div>
        <div className={style.content}>
          <h1 className="t-inter-semi-bold">Reveal Your True Self</h1>
          <p className="t-inter-medium">
            A creative ID that showcases your personality
          </p>
          <Input
            placeholder="Search .mina Names"
            value={value}
            className={style.input}
            onChange={(e) => setValue(e.target.value)}
            variant={InputVariant.search}
          />
          {resultContent.isShow && <ResultItem text={resultContent.text} className={style.resultItem}/>}
        </div>
      </div>
    </>
  );
}
