import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./variables.css";
import "./theme.css";
import OverlayWrapper from "@/components/molecules/popupOverlay/overlayWrapper";

import style from "./layout.module.css";
import { Header } from "@/components/sections/header";

const inter = Inter({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mina Names",
  description: "Generated by create next app",
};
import Store from "@/store";
import ModalContainer from "@/components/molecules/modals/modalsContainer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={inter.className}>
        <Store>
          <OverlayWrapper />
          <ModalContainer />
          <div className={style.wrapper}>
            <Header />
            {children}
          </div>
        </Store>
      </body>
    </html>
  );
}
