name: Frontend Deploy

inputs:
  workdir:
    default: '.'
  webroot:
    description: The root directory of the web server that will be used to search for a file
    required: true
  systemd_service:
    description: Systemd service name
    required: true
  ssh_hostname:
    description: SSH hostname
    required: true
  ssh_username:
    description: SSH username
    required: true
  ssh_password:
    description: SSH password
    required: true
  github_token:
    description: GitHub Personal Access Token (PAT)
    required: true

runs:
  using: composite
  steps:
  - name: Login to GitHub Packages
    shell: sh
    run: |
      cat > .npmrc <<-EOF
        //npm.pkg.github.com/:_authToken=${{ inputs.github_token }}
        @staketab:registry=https://npm.pkg.github.com
      EOF

  - name: Setup SSH Connection
    shell: sh
    run: |
      mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh
      ssh-keyscan ${{ inputs.ssh_hostname }} >> $HOME/.ssh/known_hosts 2>/dev/null

  - name: Install pnpm
    uses: pnpm/action-setup@v3
    with:
      version: 8
      run_install: false

  - name: Install NPM dependencies
    working-directory: ${{ inputs.workdir }}
    shell: sh
    run: pnpm install

  - name: Build project
    working-directory: ${{ inputs.workdir }}
    shell: sh
    run: pnpm run build

  - name: Deploy compiled project to the remote server
    shell: sh
    run: |
      sshpass -p "${{ inputs.ssh_password }}" \
        ssh ${{ inputs.ssh_username }}@${{ inputs.ssh_hostname }} rm -rf ${{ inputs.webroot }}/*

      sshpass -p "${{ inputs.ssh_password }}" \
        rsync \
          --archive \
          --verbose \
          --human-readable \
          --delete-before \
          ${{ inputs.workdir }}/ ${{ inputs.ssh_username }}@${{ inputs.ssh_hostname }}:${{ inputs.webroot }}/

      sshpass -p "${{ inputs.ssh_password }}" \
        ssh ${{ inputs.ssh_username }}@${{ inputs.ssh_hostname }} "sudo systemctl restart ${{ inputs.systemd_service }}"
