import { Navigation } from "@/components/organisms/navigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import style from "./index.module.css";
import OverlayWrapper from "@/components/molecules/popupOverlay/overlayWrapper";

const inter = Inter({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mina Names",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={inter.className}>
        <div className={style.wrapper}>
          <OverlayWrapper />
          <Navigation />
          <div className={style.content}>{children}</div>
        </div>
      </body>
    </html>
  );
}
